### ISSUE TITLE
The un-monkeypatching in AsyncioHub might be too aggressive

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#1012]
Context:
1. We want `asyncio` module to use blocking APIs.
2. Therefore, we have a song-and-dance in `AsyncioHub.__init__` to make sure they're loaded with `original("socket")` and friends instead of `socket` and friends.

The problem is that may impact transitive modules (modules imported by `asyncio`) where we want to stick to greened APIs. So maybe some sort of more fine grained unmonkeypatching mechanism should be used, in which case we can maybe:

1. Move it to `monkey_patch()`.
2. Maybe rip out the whole check-for-early-asyncio import thing?

**Comment by 4383** [comment]
My original thinking was that to get the peace of mind with the asyncio hub we should unpatch all the things:

https://github.com/eventlet/eventlet/pull/930#discussion_r1521130548

So maybe we have to modify a bit the monkey_patch mechanisms to be more oriented to hubs needs.
I don't know if it is feasible, but maybe moving the monkey patch after the hub definition and then base the monkey patching on the loaded hub and then only apply the right needs from case to case and forbid users to patch such or such modules by checking the loaded hub at monkey patching calls.

My empirical understanding is that in all the case, these two notions (monkey patching and hubs) are strongly linked.

**Comment by itamarst** [comment]
I think I'm gonna go with monkey_patch() undoing some monkey patching in the asyncio parts of stdlib if the asyncio hub is used.

**Comment by 4383** [comment]
and maybe forbid users to load new hubs at flight once the monkey patching is already applied. That would surely force the users to use `[EVENTLET_HUB](https://eventlet.readthedocs.io/en/latest/environment.html#env-vars)` and then maybe we would have to remove access to `[eventlet.hubs.use_hub](https://eventlet.readthedocs.io/en/latest/hubs.html#eventlet.hubs.use_hub)`.

Hence, the paradigm would be more: select your hub as soon as possible rather than monkey patch as soon as possible.

The default hub would remain the same, and if the personalised hub is not given at start, then, it would not be possible to change it at runtime, hence given us all the latitude to define tailored monkey patches for each needs.

**Comment by 4383** [comment]
and all monkey patching made at runtime would be secured by safety net, forbidding patching such or such things because the hub do not allow it.

**Comment by itamarst** [comment]
monkey_patch() loads the hub, so you can't really choose a hub after that anyway.

In general I want to minimize changes because this is all oh-so-fragile.
