### ISSUE TITLE
Backport of #135 to 0.14.0 ready for review

### ISSUE THREAD

**Issue by six8** [eventlet/eventlet#221]
I've backported the fix to #135 to get Python 2.7.9 compatibility. We can't upgrade to 0.14+ yet. I can't do a pull request because there's only a tag for 0.14. Can a v0.14 branch be created so I can PR?

Relevant fix is at https://github.com/pulsesecure/eventlet/tree/135-backport-sslwrap

**Comment by temoto** [comment]
Hello, @six8 

* Eventlet project does not require forks and pull requests. You can send in old school patches or just pieces of code using any transport convenient for you.
* Granted there would be v0.14 branch, I frankly don't know what to do with it:
* We don't change old release tarballs on PyPi, because that would mean inconsistency: several states of code are called by same version number. Issues for everyone.
* We don't backport patches to old releases. Please, explain me the point of doing so? It seems creating v0.14.1 or similar wouldn't help because you can't upgrade to 0.14+ yet.

**Comment by six8** [comment]
I created 0.14.1 and that's what I'm using, only from my fork. What I really meant was I can't upgrade to 0.15+.

**Comment by temoto** [comment]
@six8 please note you may also need this patch https://github.com/eventlet/eventlet/commit/b2e5146dec8f6fe075884dcf788f64a16bc3fec3 for SSL client connections. Affects httplib which is used by almost every Python HTTP client. Are you willing to test these two patches together?

**Comment by six8** [comment]
Ah, I see. Will do.

**Comment by temoto** [comment]
Is this issue still relevant?

**Comment by six8** [comment]
Probably not. We're using the patched version and it's working for us. Best option would of course be to upgrade to a newer eventlet. If I ever add the other patch and test I'll re open PR.
