### ISSUE TITLE
Perhaps eventlet wsgi should switch out of chunked-read mode when consuming message body?

### ISSUE THREAD

**Issue by portante** [eventlet/eventlet#242]
The code at line 516 of wsgi.py at the time of this writing consumes the body of the message when cleaning up the connection (see #27).  If the chunked encoding is somehow bad, it appears that in this case the body won't get read properly, as the chunked-read code can raise a ValueError and terminate that loop.

Is it worth fixing that code to force a non-chunked read behavior?

**Comment by temoto** [comment]
Thank you. Yes, it looks good for me to me to consume the rest of failed request ignoring chunked encoding.

**Comment by temoto** [comment]
Hello, @portante .
I think I fixed it by closing connection on `ChunkReadError` and skipping discard altogether when connection was marked for closing anyway. It took me two years to realise #27 has had this condition in title. And then original proposal in that issue makes full sense. Discarding request body is only useful for persistent connections.
It could not be generic `while sock.recv(4096): pass` loop because that would also consume next request header and hang until timeout.

What do you think about this commit? b443de3

**Comment by portante** [comment]
@temoto, left a comment about discards in the non-chunked case.  Seems like we might need to discard up to `content_length - position` bytes, but perhaps I am not understanding how things work here.  What do you think?

**Comment by temoto** [comment]
Fix is merged in master, requests with declared `Content-Length` are expected to drain properly too.
