### ISSUE TITLE
eventlet on Python 3.5 seems to hang threading

### ISSUE THREAD

**Issue by ctolsen** [eventlet/eventlet#249]
Demonstrated by the following:

```python
import eventlet
eventlet.monkey_patch()

import threading

from http.server import HTTPServer, BaseHTTPRequestHandler
server = HTTPServer(('localhost', 8001), BaseHTTPRequestHandler)
thread = threading.Thread(target=server.serve_forever)
thread.start()
print('thread started')
server.shutdown()
```

Pasting that into a python 3.5 REPL will hang on the `thread.start()` call. If you remove the `eventlet.monkey_patch()` call, however, everything works as expected.

Any idea what might be going on here?

**Comment by jstasiak** [comment]
@ctolsen An interesting bug to discover, I have it fixed in a branch: https://github.com/eventlet/eventlet/commit/a24a583173f212fb48960c0a2e84eb05ac48523d

@temoto Can you have a look at that patch? I went with replacing all selectors with ``SelectSelector`` but deleting them should be just as easy.

Related: https://github.com/eventlet/eventlet/issues/169

**Comment by jstasiak** [comment]
I just merged that fix into the master branch.

**Comment by temoto** [comment]
Reverted.

https://travis-ci.org/eventlet/eventlet/builds/92613900

When some builds fail, it may be due to busy hardware. When all (but pep8) builds fail, there is something wrong. Please, don't merge that in master.

I'm sure that there's some small thing preventing from accurate counting of multiple readers.

**Comment by temoto** [comment]
Sorry for not replying earlier.

**Comment by jstasiak** [comment]
@temoto It's not this, it's https://github.com/eventlet/eventlet/commit/4656eadfa5ae1237036a63ad4004dbee4572debf that breaks it; I'll revert.

**Comment by jstasiak** [comment]
PS. All tests have been successful on my machine, I'd not have merged the code otherwise. More debugging to do.

**Comment by jstasiak** [comment]
This is back in the master branch, closing.
