### ISSUE TITLE
wsgi log Timestamps for Accepted messages

### ISSUE THREAD

**Issue by audrummer15** [eventlet/eventlet#367]
Right now, our prod logs look like this: 

```
(893) accepted ('127.0.0.1', 59580)
(893) accepted ('127.0.0.1', 59590)
(893) accepted ('127.0.0.1', 59591)
(893) accepted ('127.0.0.1', 59592)
(893) accepted ('127.0.0.1', 59593)
```
... over and over again. Which isn't really useful at all. It would be nice if there were some way to add a timestamp to this message, or disable it because it bloats our logs. I believe the place this would be happening is at the following line:
https://github.com/eventlet/eventlet/blob/4d2cdca17a44b19405d4cdeafc898a500fe2485c/eventlet/wsgi.py#L882

If I'm missing something, please let me know.

**Comment by temoto** [comment]
I agree this format is not very useful. Probably our wsgi server needs rethink of logging. This is not a priority task because more general customization approach is available, but patches are always welcome.

Right now your best option is to construct an `logging.Logger` interfaced object (that means it has `debug`, `info`, `error`, etc methods). And pass it to `wsgi.Server(log=foo)`. In those methods you can apply any custom filters or formatting.
