### ISSUE TITLE
Monkey patched Queue is missing mutex attribute

### ISSUE THREAD

**Issue by fgaudin** [eventlet/eventlet#415]
I'm getting the error when using kombu (messaging library used by Celery) with gunicorn and eventlet.

Here is the original ticket that I brought up on the Kombu side: https://github.com/celery/kombu/issues/741
A demo project showing the bug: https://github.com/fgaudin/kombu_eventlet_bug

And it fails because of this part of the code https://github.com/celery/kombu/blob/836512cadd23c96f23bbb5cd8f4a1bf83c36ab19/kombu/resource.py#L193

**Comment by temoto** [comment]
I'm sorry, my resolution is wontfix.

You can patch `eventlet.LifoQueue` with noop mutex and it will work. I tried a little and can't figure how to add it to our code. Ideas or patches are very welcome. It must actually guard modifications but also don't add significant overhead.

We just don't have that mutex, our queue is probably better than stdlib :-) Could add noop mutex just to match interface, but that's a lie. Could actually guard mutations with mutex but that's performance penalty for no reason.

Yes, `Queue` `.queue` and `.mutex` attributes don't start with underscore, which makes them "public". But they're undocumented which kinda makes them private or at least implementation detail. One can build a decent queue with double linked list for all I know.

Another argument: you know you're doing something fishy if your code reads

* `len(Queue.queue)` instead of documented method `Queue.qsize()`
* `Queue.queue.popleft()` instead of documented `Queue.pop()` - *this one is asking for trouble*. Sometime Python may add useful code to `Queue.pop` which will not be executed by Kombu and will break badly. Again, it is technically public, but IMHO don't touch it because undocumented and it's obviously messing with internals.

I can understand why @ask done it this way, but respectfully disagree.
