### ISSUE TITLE
Is it crazy to deploy a WSGI application with eventlet on the open internet?

### ISSUE THREAD

**Issue by plainas** [eventlet/eventlet#440]
I have a rest API I need to deploy on the internet. Everywhere, all I see is people talking about how these things are great behind nginx. But to be frank, I find this situation a bit boring. Simpliciry of a setup without the need for proxies is, in my opinion, hugely undervalued.
Note that I have virtually no static content to serve. I can't see how a proxy could help performance in here.

Apart from maybe swagger specs and swagger ui, my REST API won't receive massive traffic. I am talking about tens of thousands of requests per day, eventually hundreds of thousands. In all honesty, I don't see why eventlet (or cherry.py, gevent, gunicorn) wouldn't handle this kind of traffic. I believe they can take such traffic and more. But the question is more about security and reliability.

Are there people doing this? Deploying WSGI apps eventlet on customer facing apps? Or does everyone put nginx in front of it? Is there any strong reason not to do it?

**Comment by temoto** [comment]
Simplicity is awesome. For your fun projects - by all means, do it. For customer apps - don't.

There was never an issue related to performance. Backend will be the bottleneck anyway.

Security is an issue here. There are many thousands of man-hours put into testing of nginx, few CVE found and fixed. I believe Python stdlib HTTP server has low hanging fruits which could be found maybe by an automated security scanner.

If not for remote code execution, it is surely not hard to do DoS for Python WSGI server.

**Comment by plainas** [comment]
I am talking about eventlet 'sporting wsgi server. Not python's stdlib implementation, which states it's not intended for production.

**Comment by plainas** [comment]
Sorry about the typo. I am replying from my mobile. I mean: eventlet's own wsgi server.

**Comment by temoto** [comment]
Eventlet's own WSGI server is horrible mix of Python stdlib BaseHTTPServer, good and bad custom stuff.

https://github.com/eventlet/eventlet/blob/7f53465578543156e7251e243c0636e087a8445f/eventlet/wsgi.py

`class HttpProtocol(BaseHTTPServer.BaseHTTPRequestHandler):`
`class Server(BaseHTTPServer.HTTPServer):`

At first, these things might look like good idea to reuse existing code from stdlib. Few years later I only feel guilt for having that instead of custom code written from scratch. It's not happening because

* personally, I believe WSGI is bad idea in first place - application/framework should speak native HTTP, there is only added cost and no benefit with proxy protocol
* WSGI server is not Eventlet business, we do concurrency, not protocols - pick a decent library that does one thing well; it will work out of box if WSGI library is orthogonal to concurrency model (how it should be)
* community is cool about state of matters and nobody sent (yet) a better replacement for our WSGI code

**Comment by plainas** [comment]
I see. Thank you. It is a bit confusing having it in the first place though. There are dozens of wsgi servers out there, most of them a simple pip install away. Puzzles me that every web frameowrk or concurrency library adds its own wsgi implementation though.

**Comment by temoto** [comment]
According to copyright comment, Eventlet WSGI dates back to 2005 when there weren't much choice of WSGI servers.

This one looks very promising, please try and write your opinion https://github.com/fgallaire/wsgiserver
should work with eventlet after monkey patching threading module.

Reopen issue if you need.
