### ISSUE TITLE
Support Python 3.3

### ISSUE THREAD

**Issue by graingert** [eventlet/eventlet#6]
Currently eventlet seems to support [2.4 - 2.7](https://github.com/eventlet/eventlet/blob/4a085a78188171e2b3e69a3c0658ffb74bf16a8b/setup.py#L40) however a lot of projects are moving to support Python 3 and 2 with a single code base using tools such as [six](http://packages.python.org/six/).

I'd recommend dropping support for 2.4 - 2.6, and supporting both 2.7 and 3.3 using the [six](http://packages.python.org/six/) library.

**Comment by temoto** [comment]
Thanks to huge amount of work by @jstasiak status of Eventlet Python3 support has changed from "something in development" straight to Beta. As in please try it in your real world applications because all tests pass. It will be part of v0.17 release this month.

If you find some particular issues, please don't hesitate to report them.

**Comment by vikt0rs** [comment]
@temoto should we also add python 3 to the classifiers list in setup.py to announce py3 support in pypi obviously?

**Comment by thedrow** [comment]
@temoto It's always a good idea.

**Comment by temoto** [comment]
@vikt0rs @thedrow done in v0.17.1 (on PyPi). Thanks!
