### ISSUE TITLE
Deprecating Python 2.7, 3.4 and 3.5 support

### ISSUE THREAD

**Issue by jstasiak** [eventlet/eventlet#623]
3.4 is *way* after its EOL, 2.7's corpse is suspiciously lively but I wouldn't want to deal with it and 3.5 is EOL soon, I'd like to deprecate the support for them in the next release (0.25.x?) and drop it in the next larger one (0.26.0). Any input? @temoto we talked about it few years back, what's your opinion on this now?

**Comment by jstasiak** [comment]
According to https://pypistats.org/packages/eventlet Eventlet installs are ~11% coming from Python 2.7, ~5% Python 3.5 and Python 3.4 numbers are negligible (~0.2%).

**Comment by temoto** [comment]
Hi, Jakub.

### Drop 2.7

I don't like idea of abandoning 11% installs. But yes, it's the right move. I'm going to do same with httplib2.

For all folks who are negatively affected by this decision: truly sorry, I could still backport some bugfixes onto 2.7 compatible version but really not for long.

### Drop 3.4

Seems perfectly reasonable to me. Especially since 3.5 introduced interrupted syscall retries which is very relevant to eventlet.

### Drop 3.5

On quick glance I didn't see any benefits to dropping 3.5. Please say.

**Comment by jstasiak** [comment]
Fair enough on Python 3.5, I had in mind some differences but turns out they're not really relevant here so I retract that point. I'd still like to drop 2.7 as the contributor resources are already spread thin and I don't like the idea of trying to satisfy Python 2.7 the next time I write or merge a patch, not in my free time (if someone paid me to do it it'd be a different story).

**Comment by temoto** [comment]
By "backport some bugfixes onto 2.7 compatible version" I meant PyPI release, not live branch.

**Comment by jstasiak** [comment]
So I forgot about this subject. Are we fine with deprecating 2.7 and 3.4? I can cut a PR with an updated docs to say this (+ maybe a runtime warning on import).

**Comment by hugovk** [comment]
> ### Drop 3.5
> On quick glance I didn't see any benefits to dropping 3.5. Please say.

f-strings! It's also now EOL.

**Comment by jstasiak** [comment]
Not a significant reason for us, but I'll take it anyway ;)

**Comment by temoto** [comment]
> So I forgot about this subject. Are we fine with deprecating 2.7 and 3.4? I can cut a PR with an updated docs to say this (+ maybe a runtime warning on import).

Deprecating - definitely yes. With big letter announcement in readme and website. BTW, that pypistats show that py2 downloads are steadily decreasing, that's comforting.
