### ISSUE TITLE
RuntimeError("Already running!") with asyncio hub

### ISSUE THREAD

**Issue by 1db1** [eventlet/eventlet#906]
First off, thanks to the contributors for the amazing eventlet/asyncio hub. But there is one problem.

I need a graceful shutdown for my service. I use something like this:

```
import asyncio
import eventlet
from eventlet import wsgi
from eventlet.asyncio import spawn_for_awaitable

eventlet.hubs.use_hub("eventlet.hubs.asyncio")
eventlet.monkey_patch()

async def run():
    while True:
        try:
            print("I'm alive")
            await asyncio.sleep(3)
        except asyncio.CancelledError:
            break

    print("Task finished")

async def cleanup(task):
    task.cancel()
    await task

def hello_world(env, start_response):
    if env['PATH_INFO'] != '/':
        start_response('404 Not Found', [('Content-Type', 'text/plain')])
        return ['Not Found\r\n']
    start_response('200 OK', [('Content-Type', 'text/plain')])
    return ['Hello, World!\r\n']

loop = asyncio.get_event_loop()
task = loop.create_task(run())
wsgi.server(eventlet.listen(('', 8080)), hello_world)
spawn_for_awaitable(cleanup(task)).wait()
```

The result is that I get the exception RuntimeError("Already running!")

As a workaround, I'm just logging the message instead of `raise RuntimeError("Already running!")`, but I'd like to have a fix.

**Comment by itamarst** [comment]
As an aside, we recommend migrating off of eventlet, so just keep in mind that's the goal of the asyncio hub, to make that migration easier. We do not recommend creating new projects that use eventlet.

I will run the reproducer, thanks for providing it.

**Comment by itamarst** [comment]
So what's happening is, when you hit Ctrl-C the asyncio loop _ends_. So the RuntimeError isn't quite right, the issue is that you're trying to start a dead event loop. I think this is the expected behavior.

The general solution for this sort of thing is having signal handlers, as described e.g. here https://www.roguelynn.com/words/asyncio-graceful-shutdowns/

**Comment by 4383** [comment]
I agree with @itamarst, if you start a new project, please consider using asyncio rather than eventlet + asyncio hub.
If for some reasons you need to provide blocking and non-blocking behavior in the same API/code, then I'd suggest to you to use a kind of facade pattern to implement blocking functions over non-blocking code.

Here is a PoC I made to test this pattern https://github.com/4383/snippets/blob/main/python/facade/facade.py Do not hesitate to inspire or copy from it.

I myself inspired from the design of edgedb-python https://www.edgedb.com/docs/clients/python/usage#edgedb-python-examples . You should take a look to the code base of edgedb-python https://github.com/edgedb/edgedb-python.
