### ISSUE TITLE
eventlet.net is 404'ing all links

### ISSUE THREAD

**Issue by jayofdoom** [eventlet/eventlet#909]
https://eventlet.net/, listed as the website for this project and returned in many google results for "eventlet BLAH", is returning 404s for almost everything.

This should be fixed rapidly or else Google pagerank for the website may be lost forever.

**Comment by 4383** [comment]
Hey @jayofdoom,

Yeah, I know the eventlet domain return a 404.
We recently moved our documentation to readthedocs => https://eventlet.readthedocs.io/en/latest/
and I recently opened a discussion (https://github.com/eventlet/eventlet/issues/824#issuecomment-1904687939) with @nat-goodspeed concerning the redirection of this domain to our new hosting platform. Unfortunatelly for now I've no news and I don't know if Nat would be able to migrate this domain by adding the requested new DNS entries.

I just submitted a new patch to redirect the domain toward readthedocs by using a javascript tricks, unfortunatelly, weeks ago, when our previous migration was done, I disabled gh-pages, and I don't know why  I'm not able to re-enable them now, I suppose it is due to my github rights level.

https://github.com/eventlet/eventlet/pull/910

**Comment by 4383** [comment]
In all the case, all our links are now refering the new documentation hosting. github, pypi, etc... also refers to this new domain, so, even if the domain is not responding, I think the community would be able to retrieve the documentation properly. 

I also think that the new hosting (with the new url) will soon, if it has not already been done, be referenced by search engine robots.
